services:
  - docker
branches:
  only: [master]
stages:
  - test
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
  - stage: test
    name: "Run Tests"
    script:
      - make build test
  - stage: deploy
    name: "Deploy to Docker Hub"
    script:
      - make deploy
before_install:
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
  -in .env.enc -out .env -d
